// Generated by CoffeeScript 1.12.6
(function() {
  var a, b;

  a = 1;

  b = function(arg1, arg2) {
    console.log(arg1);
    console.log(arg2);
  };

}).call(this);

//# sourceMappingURL=expected.js.map
